language: ruby
rvm:
  - 2.1
env:
  - DB=postgres
before_script:
  - psql -c 'create role ulmicru with createdb login;' -U postgres
before_install:
  - gem install bundler
script:
  - sudo pip install ansible
  - make deps
  - ansible-playbook -i cm/inventory cm/playbook.yml --tags 'test'
  - RAILS_ENV=test bundle exec rake db:create db:migrate test
services:
  - redis-server
