default: &default
  username: postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: develop
  database: ulmic_development
test:
  adapter: postgresql
  database: ulmic_test
  pool: 5
  timeout: 5000

staging:
  <<: *default
  username: mic
  database: ulmic_staging

production:
  <<: *default
  username: mic
  database: ulmic_production
